name: DataSchemaCodeConvention
on:
  push:
    branches: main 
jobs:
  sql_linter_test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: "actions/checkout@v3"
      - name: Start SQL Schema Linter
        run: |
          npm install -g sql-lint
          sql-lint $GITHUB_WORKSPACE/DataSchema.sql
